chore: Update minor and patch Golang dependencies (#648)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [github.com/goccy/go-yaml](https://redirect.github.com/goccy/go-yaml)
| `v1.15.22` -> `v1.15.23` |
[![age](https://developer.mend.io/api/mc/badges/age/go/github.com%2fgoccy%2fgo-yaml/v1.15.23?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/go/github.com%2fgoccy%2fgo-yaml/v1.15.23?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/go/github.com%2fgoccy%2fgo-yaml/v1.15.22/v1.15.23?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/go/github.com%2fgoccy%2fgo-yaml/v1.15.22/v1.15.23?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [github.com/nobl9/govy](https://redirect.github.com/nobl9/govy) |
`v0.11.0` -> `v0.12.1` |
[![age](https://developer.mend.io/api/mc/badges/age/go/github.com%2fnobl9%2fgovy/v0.12.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/go/github.com%2fnobl9%2fgovy/v0.12.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/go/github.com%2fnobl9%2fgovy/v0.11.0/v0.12.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/go/github.com%2fnobl9%2fgovy/v0.11.0/v0.12.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>goccy/go-yaml (github.com/goccy/go-yaml)</summary>

###
[`v1.15.23`](https://redirect.github.com/goccy/go-yaml/releases/tag/v1.15.23):
1.15.23

[Compare
Source](https://redirect.github.com/goccy/go-yaml/compare/v1.15.22...v1.15.23)

#### What's Changed

- Fix encoding of string that contains "- " by
[@&#8203;goccy](https://redirect.github.com/goccy) in
[https://github.com/goccy/go-yaml/pull/657](https://redirect.github.com/goccy/go-yaml/pull/657)

**Full Changelog**:
https://github.com/goccy/go-yaml/compare/v1.15.22...v1.15.23

</details>

<details>
<summary>nobl9/govy (github.com/nobl9/govy)</summary>

###
[`v0.12.1`](https://redirect.github.com/nobl9/govy/releases/tag/v0.12.1)

[Compare
Source](https://redirect.github.com/nobl9/govy/compare/v0.12.0...v0.12.1)

### What's Changed

#### ⚠️  Breaking Changes

- fix: Correct joinStringSlice template function usage
([#&#8203;76](https://redirect.github.com/nobl9/govy/issues/76))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
> Changed template function name from `joinStringSlice` to `joinSlice`
to better reflect its usage.

#### 🐞 Bug Fixes

- fix: Correct joinStringSlice template function usage
([#&#8203;76](https://redirect.github.com/nobl9/govy/issues/76))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
> Template function `joinStringSlice` was renamed to `joinSlice` and it
now accepts any kind of slice, not only a slice of strings.

###
[`v0.12.0`](https://redirect.github.com/nobl9/govy/releases/tag/v0.12.0)

[Compare
Source](https://redirect.github.com/nobl9/govy/compare/v0.11.0...v0.12.0)

### What's Changed

#### ⚠️  Breaking Changes

- feat: Add templating to all the builtin rules
([#&#8203;74](https://redirect.github.com/nobl9/govy/issues/74))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
> `rules.OneOf` error has been changed, instead of `must be one of
[this, that]` it will now return `must be one of: this, that`.
- feat: Add WithExamples function to rules
([#&#8203;59](https://redirect.github.com/nobl9/govy/issues/59))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
> The following rules no longer support providing examples as arguments
directly to the rule constructor: `StringMatchRegexp`,
`StringDenyRegexp`, `StringDateTime`. Instead, provide these examples by
calling `WithExamples` method of the `govy.Rule`, e.g.:
`rules.StringMatchRegexp(regexp.MustCompile("^John|Jack$")).WithExamples("John",
"Jack")`.
- chore: Remove details from govy.RuleError
([#&#8203;60](https://redirect.github.com/nobl9/govy/issues/60))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
> Removed `govy.RuleError.Details` field, the error's details are now
part of the `govy.RuleError.Message` and not just the
`govy.RuleError.Error()` output.

#### 🚀 Features

- feat: Add templating to all the builtin rules
([#&#8203;74](https://redirect.github.com/nobl9/govy/issues/74))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
- feat: Introduce message templates
([#&#8203;10](https://redirect.github.com/nobl9/govy/issues/10))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
> Added `govy.Rule.WithMessageTemplate` and
`govy.Rule.WithMessageTemplateString` functions which allow advanced
manipulation of the error message produced by `govy.Rule`.
> Users can add templating support to their rules by returning a new
error: `govy.RuleErrorTemplate`.
> This error is a simple container that passes `govy.TemplateVars` to
the rule evaluation logic which uses it as variables to execute an error
message template.
> User defined variables should be provided via
`govy.TemplateVars.Custom` field which accepts `any` value.
> Added `govy.AddTemplateFunctions` which adds builtin template
functions to the user's `template.Template` instance.
- feat: Add WithExamples function to rules
([#&#8203;59](https://redirect.github.com/nobl9/govy/issues/59))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
> Added `WithExamples` method to `govy.Rule` which allows adding
examples to the produced error message.
> The examples are converted to their string representation and added
between error message and details, like so: `<message> (e.g.
<examples>); <details>`.

#### 🐞 Bug Fixes

- fix: Use custom logger instead of modifying slog.Default logger
([#&#8203;68](https://redirect.github.com/nobl9/govy/issues/68))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
    > Govy no longer overwrites the default `slog` logger.

#### 🧰 Maintenance

<details>
<summary>8 changes</summary>

- chore: Improve docs for errore message templates
([#&#8203;75](https://redirect.github.com/nobl9/govy/issues/75))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
- chore: Correct benchmarks
([#&#8203;72](https://redirect.github.com/nobl9/govy/issues/72))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
- chore: Update jetpack-io/devbox-install-action action to v0.12.0
([#&#8203;65](https://redirect.github.com/nobl9/govy/issues/65))
@&#8203;[renovate\[bot\]](https://redirect.github.com/apps/renovate)
- chore: Update dependency cspell to v8.17.1
([#&#8203;57](https://redirect.github.com/nobl9/govy/issues/57))
@&#8203;[renovate\[bot\]](https://redirect.github.com/apps/renovate)
- chore: Exclude validator comparison module from Renovate
([#&#8203;62](https://redirect.github.com/nobl9/govy/issues/62))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
- chore: Remove details from govy.RuleError
([#&#8203;60](https://redirect.github.com/nobl9/govy/issues/60))
[@&#8203;nieomylnieja](https://redirect.github.com/nieomylnieja)
- chore: Update dependency cspell to v8.16.1
([#&#8203;56](https://redirect.github.com/nobl9/govy/issues/56))
@&#8203;[renovate\[bot\]](https://redirect.github.com/apps/renovate)
- chore: Update dependency markdownlint-cli to v0.43.0
([#&#8203;55](https://redirect.github.com/nobl9/govy/issues/55))
@&#8203;[renovate\[bot\]](https://redirect.github.com/apps/renovate)

</details>

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "* 0-4,22-23 * * 1-5,* * * * 0,6"
(UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/nobl9/nobl9-go).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xNjcuMSIsInVwZGF0ZWRJblZlciI6IjM5LjE2Ny4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiLCJnb2xhbmciLCJyZW5vdmF0ZSJdfQ==-->

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Mateusz Hawrus <mateusz.hawrus@nobl9.com>