fix: Don't allow for anomaly_config in Composite v2 spec (#841)
## Motivation

Composites 2.0 do not use direct metrics (`raw_metric`,
`good_count_metric`, etc...) which are required for proper evaluation of
No Data anomalies.

## Summary

- Updated SLO spec validation to forbid spec.anomalyConfig whenever
Spec.HasCompositeObjectives() is
    true (i.e., for Composite SLO 2.0).
- Left behavior unchanged for non-composite SLOs and legacy composite
SLOs using spec.composite.
- Added a unit test to manifest/v1alpha/slo/validation_composite_test.go
asserting a Forbidden error on
    spec.anomalyConfig for a valid composite SLO with anomalyConfig set.

## Testing

- go test ./manifest/v1alpha/slo -run TestValidate_CompositeSLO

Scenarios: 
Try to apply such yaml:
```
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: adam-test-minimal-composite-v2
    displayName: adam-test-minimal-composite-v2
    project: appdynamics
    labels:
      composite:
      - "true"
  spec:
    description: ""
    budgetingMethod: Occurrences
    objectives:
    - displayName: ""
      name: composite-objective
      target: 0.92
      composite:
        maxDelay: 1m
        components:
          objectives:
          - project: appdynamics
            slo: appdynamics-direct
            objective: good
            weight: 1.0
            whenDelayed: Ignore
          - project: appdynamics
            slo: appdynamics-polakpotrafi-end-user-response-count-calendar
            objective: objective-1
            weight: 1.0
            whenDelayed: Ignore
          - project: appdynamics
            slo: appdynamics-polakpotrafi-end-user-response-count-calendar
            objective: objective-2
            weight: 1.0
            whenDelayed: Ignore
          - project: appdynamics
            slo: appdynamics-polakpotrafi-end-user-response-count-rolling
            objective: objective-1
            weight: 1.0
            whenDelayed: Ignore
          - project: appdynamics
            slo: appdynamics-polakpotrafi-end-user-response-count-rolling
            objective: objective-2
            weight: 1.0
            whenDelayed: Ignore
    service: appdynamics-polakpotrafi-service
    timeWindows:
    - unit: Month
      count: 1
      isRolling: false
      calendar:
        startTime: "2024-12-01 00:00:00"
        timeZone: UTC
      period:
        begin: "2025-11-01T00:00:00Z"
        end: "2025-12-01T00:00:00Z"
    createdAt: "2025-10-23T13:44:16Z"
    createdBy: 00uoc6fwq2Cf9QibU4x6
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
        alertAfter: 30m
  status:
    updatedAt: "2025-11-18T09:29:00Z"
    review:
      status: notStarted
```

It should throw validation error.

```
Applying 1 objects from the following sources: 
 - v2.yaml
Error: Bad Request: Validation for SLO 'adam-test-minimal-composite-v2' in project 'appdynamics' has failed for the following fields:
  - 'spec.anomalyConfig' with value '{"noData":{"alertMethods":[{"name":"slack-notification","project":"default"}],"alertAfter":"30m"}}':
    - property is forbidden; anomalyConfig section is forbidden when spec.objectives[0].composite is provided
Manifest source: v2.yaml (code: 400, endpoint: PUT https://dev-mint.nobl9.dev/api/apply?dry_run=false, traceId: 2057157466853419811)
```


## Release Notes

- anomalyConfig section in SLO definition is no longer allowed for
Composite 2.0